name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  boilerplate:
    name: boilerplate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: apimachinery
      - uses: actions/checkout@v3
        with:
          repository: kubernetes/repo-infra
          ref: master
          path: repo-infra
          fetch-depth: 1
      - run: |
          cd apimachinery
          ../repo-infra/hack/verify_boilerplate.py --boilerplate-dir=hack/boilerplate

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: v1.18
      - name: Run golangci-lint
        run: make lint

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: v1.18
      - run: make test
